### ISSUE TITLE
[Backend] release the necessary migration scripts to make the backend work

### ISSUE THREAD

**Issue by majbbtech** [MarsX-dev/devhunt#103]
There is no migration scripts or database schema including views, functions that require backend to work locally. Self-hosting is not possible without this. Happy to help if needed.

**Comment by majbbtech** [comment]
Especially, it would be great to get the backend logic embedded in the functions, views and RLS policies. Thanks

**Comment by sidiDev** [comment]
@majbbtech Hey thanks for opening this issues, we will look into that.

**Comment by sidiDev** [comment]
@majbbtech Hey, now you can run it locally, please check the home page of the repository.
