### ISSUE TITLE
[Feature Request] Dark mode and light mode

### ISSUE THREAD

**Issue by d0nda** [MarsX-dev/devhunt#127]
hey , i love what you guys are building and id like to contribute by starting with dark mode and light mode feature ...

**Comment by sidiDev** [comment]
@d0nda Hey there, thanks for opening this issue, let’s think about this and back to you.
cc @johnrushx

**Comment by d0nda** [comment]
ok great, looking forward to the response. i was also wondering about the landing page are the plans to revamp it  anytime soon ?

**Comment by sidiDev** [comment]
> ok great, looking forward to the response. i was also wondering about the landing page are the plans to revamp it anytime soon ?

@d0nda I don’t think so, because the most important thing now is to get people to launch their tools or search for new tools,
but maybe later when DevHunt becomes big then we’ll rebuild it and do a lot of code refactoring ...etc.

**Comment by sidiDev** [comment]
@d0nda Hey there, after I discussed with the team, we don’t think we gonna have light mode for this dev tool at the moment.
And we really appreciate your interest in contributing, but don’t stop, go ahead if you have something else you want to contribute to :)
