### ISSUE TITLE
Create user information page

### ISSUE THREAD

**Issue by mohamed-abdelahi-haibelty** [MarsX-dev/devhunt#21]
`The page will include` :
1. Avatar with a change button.
2. Username field.
3. About field.
4. Email field.
5. Cover upload.
6. Save button.

**Comment by sidiDev** [comment]
@mohamed-abdelahi-haibelty Hi Mohamed, this is a good task, but don't add Cover upload there, it's not necessary now.

**Comment by mohamed-abdelahi-haibelty** [comment]
> @mohamed-abdelahi-haibelty Hi Mohamed, this is a good task, but don't add Cover upload there, it's not necessary now.
unfortuntaly, i've seen your message just know,  i spent so much time working on the cover upload. anyway i removed it

**Comment by mohamed-abdelahi-haibelty** [comment]
@sidiDev unfortuntaly, i've seen your message just know,  i spent so much time working on the cover upload. anyway i removed it
