### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by Dev-Ahmadubah** [MarsX-dev/devhunt#3]
Text is not having margin/padding on mobile view. This is causing the text to be too close to the edges of the screen, which can make it difficult to read.

Desktop view
![Screenshot_20230523_222614_com brave browser_edit_69470753495648](https://github.com/MarsX-dev/devhunt/assets/60859825/eb86ba97-47ef-483b-afe7-0fff2de171e3)

Mobile view
![Screenshot_20230523_222604_com brave browser_edit_69483560190959](https://github.com/MarsX-dev/devhunt/assets/60859825/f58e1af1-39ea-4073-81db-48a0d72547f3)

**Comment by sidiDev** [comment]
hey @Dev-Ahmadubah we just was working on it in that time, now everything is good, thanks.
