### ISSUE TITLE
Adding Feautres 

### ISSUE THREAD

**Issue by Youssef535** [MarsX-dev/devhunt#65]
I came across Devhunt and noticed that the sign-in process redirects me directly to the GitHub 3rd party login. To improve this, we can enhance the sign-in options by including Stackoverflow, GitHub, GitLab or allowing users to sign in with their registered email and password.

For the signup process, I have designed user-friendly software that is easy to navigate. We can incorporate forms using libraries such as Float UI, Chakra UI, or Mantine. Among these options, Zod provides excellent validation capabilities, and Superbase can be considered as well. It's important to note that some developers may be using platforms like GitLab, so offering a traditional authentication method alongside these enhancements would be a great idea.

Also I've made a simple architecture to improve the backend

**Comment by sidiDev** [comment]
@Youssef535 Hi Youssef! Thanks for opening  this issue, I think adding  google provide side of Github can be enough for now, and I would like to hear more about  architecture improvement you mentioned.

**Comment by Youssef535** [comment]
@sidiDev  sorry for the waiting i was working on a project but here is an example what do you think?
![github](https://github.com/MarsX-dev/devhunt/assets/82522735/110949ba-2fac-47e0-af81-92afcf70f086)
