### ISSUE TITLE
comments for product with ability to reply

### ISSUE THREAD

**Issue by johnrushx** [MarsX-dev/devhunt#7]
Use supabase.
Ability to add and delete comments.
also replies under comments.
mark the maker with "M" icon same as on product hunt.

**Comment by vitalikmay** [comment]
I take this task

**Comment by vitalikmay** [comment]
Someone should implement front-end

**Comment by NadaaFarook** [comment]
I can take up the frontend
How exactly should it look like ?

**Comment by sidiDev** [comment]
> I can take up the frontend How exactly should it look like ?

Hi Nadaa, the frontend was already built.
