### ISSUE TITLE
[Feature Request] Enable Hyperlink for "About Product" section and 

### ISSUE THREAD

**Issue by digracesion** [MarsX-dev/devhunt#80]
At the moment, added information about the product in its "About Product" section simply shows up as text.
Sample:

![image](https://github.com/MarsX-dev/devhunt/assets/18523823/f081fd8d-4bcf-4448-8406-b74d9c330ff7)

It would be better if this link was enabled into a hyperlink by default for easier user interaction

**Comment by sidiDev** [comment]
@digracesion Thanks for your feedback, we gonna work on that next time.
