### ISSUE TITLE
cannot find database initial script

### ISSUE THREAD

**Issue by goodclub** [MarsX-dev/devhunt#92]
cannot find database initial script

**Comment by justinchitla** [comment]
^This would be helpful. I've cloned the repo and would like to see it run successfully locally but my supabase project is empty and I can't find the db schemas. Is this something that can be provided?

**Comment by majbbtech** [comment]
@goodclub @justinchitla I think the founders might be busy but here is the reverse engineered schema, which is working with few bugs locally, hopefully I should able to fix them soon. Please try this and let me know how you go: https://gist.github.com/majbbtech/e5a9857bfbdac60582476723eb5271dc

**Comment by majbbtech** [comment]
No worries at all. I remember seeing this too, Please ensure you have setup the oAuth settings in config.toml under supabase folder file like the below example
`[auth.external.google]
enabled = true
client_id = "xxx.apps.googleusercontent.com"
secret = "xxx"
redirect_uri = "http://localhost:54321/auth/v1/callback"`

**Comment by majbbtech** [comment]
Also, check the RLS policy on profiles table.

**Comment by majbbtech** [comment]
If you're using supabase cli then config.toml is generated when you init. But anyway, you're right it could be the row is not created in the profiles table. 
<img width="1109" alt="image" src="https://github.com/MarsX-dev/devhunt/assets/88103863/9ec3e076-492d-485c-9758-221c544a2a31">

**Comment by majbbtech** [comment]
@justinchitla can you check if auth.users table has the newly created user row?

**Comment by majbbtech** [comment]
Change the schema from public to auth like this: <img width="301" alt="image" src="https://github.com/MarsX-dev/devhunt/assets/88103863/4efc875c-bfab-49ed-93b1-b67c44f06d58">

**Comment by majbbtech** [comment]
that is totally possible that, user is created but not the profile record, just for testing purpose you can create profile record using the user.id but I will share my types file too.

Wait I just say dump.sql file from the devhunt team. check it out: https://github.com/MarsX-dev/devhunt/blob/main/supabase/dump.sql

**Comment by sidiDev** [comment]
Hey sorry for being late, now you can run it locally, check the home page of the repository.
And thanks for your patience.
