### ISSUE TITLE
[Docs]: Can we have better documentation?

### ISSUE THREAD

**Issue by Dun-sin** [MarsX-dev/devhunt#96]
since this is open source, there needs to be a good readme for contributors to better understand and contribute to the project, for instance the full tools used, how to install and set up configurations and the project code standards. 

If you can provide me with that information I will help.

**Comment by sidiDev** [comment]
Hey @Dun-sin Nice to see you here, and thanks for your your thoughts, we gonna work on that.

**Comment by sidiDev** [comment]
Guys, we updated the README repo, you can now run it locally.

**Comment by sidiDev** [comment]
@justinchitla Hey mate, you can check this https://github.com/MarsX-dev/devhunt/blob/main/CONTRIBUTING.md
and if you want to run it locally check the home page of the repository.
